### ISSUE TITLE
Membership Request

### ISSUE THREAD

**Issue by markoprljic** [WalletConnect/association#2]
_We are inviting individuals and organizations to join the WalletConnect Association! The Associate Membership is open to all, other tiers are available as well. If you have any questions before submitting, please join our Discord chat https://discord.walletconnect.org_

---

Please fill out the following membership information:

Organization or Individual Name:
_Insert Name_

Website:
_www.mywebsite.com_

Logo:
_attach a logo or link to where it can be downloaded_

One-line description:
_Insert your tagline description_

Twitter handle:
_@username_

Type:
_one of Individual, Wallet, Dapp, Foundation, Organization_

Additional comments or questions:
_Feel free to add any additional comments or questions_

**Comment by bmann** [comment]
Thanks @markoprljic — I updated the default template with your suggested changes. Please file another issue with your real membership application!
